<?php
/**
 * @file
 * feature_blog.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function feature_blog_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'taxonomy_term-countries-field_flag'
  $field_instances['taxonomy_term-countries-field_flag'] = array(
    'bundle' => 'countries',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_flag',
    'label' => 'Flag',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'taxonomy_term-countries-field_official_name'
  $field_instances['taxonomy_term-countries-field_official_name'] = array(
    'bundle' => 'countries',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Please enter the official name for this country, if it is different than the common name.',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_official_name',
    'label' => 'Official Name',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Flag');
  t('Official Name');
  t('Please enter the official name for this country, if it is different than the common name.');

  return $field_instances;
}
