<?php

include_once('idap_workbench_create.inc');
include_once('idap_workbench_edit.inc');
include_once('idap_workbench_delete.inc');
include_once('idap_workbench_misc.inc');

/* Implements hook_menu() */
function idap_workbench_menu() {
	$items['admin/structure/workbench'] = array(
		'title' => t('Workbench'),
		'page callback' => 'idap_workbench_list',
		'description' => 'IDAP Workbench',
		'access callback' => 'user_access',
		'access arguments' => array('administer thematic sections'),
		'type'=>MENU_NORMAL_ITEM,
		'file' => 'idap_workbench_admin.inc'
	);
	$items['admin/structure/workbench/add'] = array(
		'title' => t('Create a new section'),
		'page callback' => 'idap_workbench_add',
		'description' => t('Create a new thematic section'),
		'access callback' => 'user_access',
		'access arguments' => array(
			'administer thematic sections',
		),
		'type' => MENU_LOCAL_ACTION,
		'file' => 'idap_workbench_admin.inc',
	);
	$items['admin/structure/workbench/%/manage-pages'] = array(
		'title' => t('Manage Pages'),
		'page callback' => 'idap_workbench_manage_pages',
		'page arguments' => array(3),
		//'title callback' => 'idap_workbench_menu_title',
		//'title arguments' => array(3,4),
		'description' => t('Lists the sub-themes that have been created on the IDAP platform'),
		'access callback' => 'user_access',
		'access arguments' => array(
			'administer thematic sections',
		),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'idap_workbench_admin.inc',
	);
	$items['admin/structure/workbench/%/manage-pages/add/landing-page'] = array(
		'title' => t('Add a section home page'),
		'page callback' => 'idap_workbench_manage_pages_add_landing_page',
		'page arguments' => array(3),
		//'title callback' => 'idap_workbench_menu_title',
		//'title arguments' => array(3,4),
		'description' => t('Lists the sub-themes that have been created on the IDAP platform'),
		'access callback' => 'user_access',
		'access arguments' => array(
			'administer thematic sections',
		),
		'type' => MENU_LOCAL_ACTION,
		'file' => 'idap_workbench_admin.inc',
	);
	$items['admin/structure/workbench/%/manage-pages/add/subpage'] = array(
		'title' => t('Add a subpage'),
		'page callback' => 'idap_workbench_manage_pages_add_subpage',
		'page arguments' => array(3),
		//'title callback' => 'idap_workbench_menu_title',
		//'title arguments' => array(3,4),
		'description' => t('Lists the sub-themes that have been created on the IDAP platform'),
		'access callback' => 'user_access',
		'access arguments' => array(
			'administer thematic sections',
		),
		'type' => MENU_LOCAL_ACTION,
		'file' => 'idap_workbench_admin.inc',
	);
	$items['admin/structure/workbench/%/delete'] = array(
		'title' => t('Delete a section'),
		'page callback' => 'idap_workbench_section_delete',
		'page arguments' => array(3),
		//'title callback' => 'idap_workbench_menu_title',
		//'title arguments' => array(3,4),
		'description' => t('Lists the sub-themes that have been created on the IDAP platform'),
		'access callback' => 'user_access',
		'access arguments' => array(
			'administer thematic sections',
		),
		'type' => MENU_CALLBACK,
		'file' => 'idap_workbench_admin.inc',
	);
	$items['admin/structure/workbench/%/edit'] = array(
		'title' => t('Edit a section'),
		'page callback' => 'idap_workbench_section_edit',
		'page arguments' => array(3),
		//'title callback' => 'idap_workbench_menu_title',
		//'title arguments' => array(3,4),
		'description' => t('Lists the sub-themes that have been created on the IDAP platform'),
		'access callback' => 'user_access',
		'access arguments' => array(
			'administer thematic sections',
		),
		'type' => MENU_CALLBACK,
		'file' => 'idap_workbench_admin.inc',
	);
	return $items;
}

function idap_workbench_menu_title($sid, $type) {
	if (!empty($type)) {
		switch ($type) {
			case 'add-landing-page':
				$title = t('Add landing page to: ');
				break;
			case 'edit':
				$title = t('Edit section: ');
				break;
			case 'delete':
				$title = t('Delete section: ');
				break;
			case 'add-subpage':
				$title = t('Add a subpage to: ');
				break;
			default:
				$title = '';
		}
	}
	
	
	$result = db_query('SELECT iw.title from {idap_workbench} iw WHERE sid = :sid', array(':sid'=>$sid));
	foreach ($result as $record) {
		$section = $record->title;
	}
			
	return $title.$section;
}

/* Implements hook_permission() */
function idap_workbench_permission() {
  	return array(
    	'administer thematic sections' => array(
      		'title' => t('Administer thematic sections'), 
      		'description' => t('Create, manage and destroy thematic sections of the IDAP site.'),
    	),
  	);
}