<?php

include_once('idap_workbench_functions.inc');

/* Implements hook_menu() */
function idap_workbench_menu() {
	$items['admin/structure/workbench'] = array(
		'title' => t('Workbench'),
		'page callback' => 'idap_workbench_overview',
		'description' => 'IDAP Workbench',
		'access callback' => 'user_access',
		'access arguments' => array('administer thematic sections'),
		'type'=>MENU_NORMAL_ITEM,
	);
	$items['admin/structure/workbench/view'] = array(
		'title' => t('View'),
		'page callback' => 'idap_workbench_view',
		'description' => t('Lists the sub-themes that have been created on the IDAP platform'),
		'access callback' => 'user_access',
		'access arguments' => array(
			'administer thematic sections',
		),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => -20,
	);
	$items['admin/structure/workbench/add'] = array(
		'title' => t('Create'),
		'page callback' => 'idap_workbench_add',
		'description' => t('Create a new thematic section'),
		'access callback' => 'user_access',
		'access arguments' => array(
			'administer thematic sections',
		),
		'type' => MENU_LOCAL_TASK,
		'file' => 'idap_workbench_admin.inc',
	);
	$items['admin/structure/workbench/delete/%'] = array(
		'title' => t('Delete'),
		'page callback' => 'idap_workbench_delete',
		'description' => t('Lists the sub-themes that have been created on the IDAP platform'),
		'access callback' => 'user_access',
		'access arguments' => array(
			'administer thematic sections',
		),
		'type' => MENU_CALLBACK,
	);
	$items['admin/structure/workbench/edit/%'] = array(
		'title' => t('Edit'), /* To do: add title callback to print name of section being edited */
		'page callback' => 'idap_workbench_edit',
		'page arguments' => array(4),
		'description' => t('Lists the sub-themes that have been created on the IDAP platform'),
		'access callback' => 'user_access',
		'access arguments' => array(
			'administer thematic sections',
		),
		'type' => MENU_CALLBACK,
		'file' => 'idap_workbench_admin.inc'
	);
	return $items;
}

/* Implements hook_permission() */
function idap_workbench_permission() {
  	return array(
    	'administer thematic sections' => array(
      		'title' => t('Administer thematic sections'), 
      		'description' => t('Create, manage and destroy thematic sections of the IDAP site.'),
    	),
  	);
}

/* Page Callback for admin/workbench */
function idap_workbench_overview() {
	return '<p>My Workbench Overview</p>';
}